// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/feed/feed.proto

package com_lcb123_srv_feed

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Feed service

type FeedService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Feed_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Feed_PingPongService, error)
}

type feedService struct {
	c    client.Client
	name string
}

func NewFeedService(name string, c client.Client) FeedService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "com.lcb123.srv.feed"
	}
	return &feedService{
		c:    c,
		name: name,
	}
}

func (c *feedService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Feed.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Feed_StreamService, error) {
	req := c.c.NewRequest(c.name, "Feed.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &feedServiceStream{stream}, nil
}

type Feed_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type feedServiceStream struct {
	stream client.Stream
}

func (x *feedServiceStream) Close() error {
	return x.stream.Close()
}

func (x *feedServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *feedServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *feedServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *feedService) PingPong(ctx context.Context, opts ...client.CallOption) (Feed_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Feed.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &feedServicePingPong{stream}, nil
}

type Feed_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type feedServicePingPong struct {
	stream client.Stream
}

func (x *feedServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *feedServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *feedServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *feedServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *feedServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Feed service

type FeedHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Feed_StreamStream) error
	PingPong(context.Context, Feed_PingPongStream) error
}

func RegisterFeedHandler(s server.Server, hdlr FeedHandler, opts ...server.HandlerOption) error {
	type feed interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Feed struct {
		feed
	}
	h := &feedHandler{hdlr}
	return s.Handle(s.NewHandler(&Feed{h}, opts...))
}

type feedHandler struct {
	FeedHandler
}

func (h *feedHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.FeedHandler.Call(ctx, in, out)
}

func (h *feedHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.FeedHandler.Stream(ctx, m, &feedStreamStream{stream})
}

type Feed_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type feedStreamStream struct {
	stream server.Stream
}

func (x *feedStreamStream) Close() error {
	return x.stream.Close()
}

func (x *feedStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *feedStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *feedStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *feedHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.FeedHandler.PingPong(ctx, &feedPingPongStream{stream})
}

type Feed_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type feedPingPongStream struct {
	stream server.Stream
}

func (x *feedPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *feedPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *feedPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *feedPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *feedPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
